ALTER TABLE public.cotizaciones
  ADD COLUMN IF NOT EXISTS anticipo_tipo TEXT NOT NULL DEFAULT 'ninguno',
  ADD COLUMN IF NOT EXISTS anticipo_valor NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS anticipo_monto NUMERIC NOT NULL DEFAULT 0;